# Generated by Django 3.1.2 on 2020-10-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_profile',
            name='photo_url',
            field=models.TextField(default='https://s3-us-west-2.amazonaws.com/adawayfarer/c4e6e5.png', max_length=255),
        ),
    ]
